package com.test.marctweet;

/**
 * Created by marc on 5/25/16.
 */
public class ParseTestData {

    /**
     * An actual response received from the server - useful for testing purposes
     * */
    public static final String SEARCH_RESPONSE = "{\n" +
            "   \"statuses\":[\n" +
            "      {\n" +
            "         \"created_at\":\"Wed May 25 09:07:40 +0000 2016\",\n" +
            "         \"id\":735396908869537792,\n" +
            "         \"id_str\":\"735396908869537792\",\n" +
            "         \"text\":\"#alice #holiday \\n\\u3042\\u308a\\u3059\\u3068\\u6620\\u753b\\u304b\\u3089\\u306e\\u304a\\u3046\\u3061\\u270c\\ufe0f\\ud83d\\udc98\\n\\u4e2d\\u5b66\\u751f\\u307f\\u305f\\u3044\\u306a\\u30c7\\u30fc\\u30c8\\u3057\\u3066\\u304d\\u305f\\ud83d\\ude4c\\nall black\\u30b3\\u30fc\\u30c7\\ud83d\\udc6f\\n#allblack #jk2 #test #\\u30e4\\u30d0\\u30a4 https:\\/\\/t.co\\/V5B5HtKUfE\",\n" +
            "         \"truncated\":false,\n" +
            "         \"entities\":{\n" +
            "            \"hashtags\":[\n" +
            "               {\n" +
            "                  \"text\":\"alice\",\n" +
            "                  \"indices\":[\n" +
            "                     0,\n" +
            "                     6\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"holiday\",\n" +
            "                  \"indices\":[\n" +
            "                     7,\n" +
            "                     15\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"allblack\",\n" +
            "                  \"indices\":[\n" +
            "                     63,\n" +
            "                     72\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"jk2\",\n" +
            "                  \"indices\":[\n" +
            "                     73,\n" +
            "                     77\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"test\",\n" +
            "                  \"indices\":[\n" +
            "                     78,\n" +
            "                     83\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"\\u30e4\\u30d0\\u30a4\",\n" +
            "                  \"indices\":[\n" +
            "                     84,\n" +
            "                     88\n" +
            "                  ]\n" +
            "               }\n" +
            "            ],\n" +
            "            \"symbols\":[\n" +
            "\n" +
            "            ],\n" +
            "            \"user_mentions\":[\n" +
            "\n" +
            "            ],\n" +
            "            \"urls\":[\n" +
            "               {\n" +
            "                  \"url\":\"https:\\/\\/t.co\\/V5B5HtKUfE\",\n" +
            "                  \"expanded_url\":\"https:\\/\\/www.instagram.com\\/p\\/BF0xjZHOK1u\\/\",\n" +
            "                  \"display_url\":\"instagram.com\\/p\\/BF0xjZHOK1u\\/\",\n" +
            "                  \"indices\":[\n" +
            "                     89,\n" +
            "                     112\n" +
            "                  ]\n" +
            "               }\n" +
            "            ]\n" +
            "         },\n" +
            "         \"metadata\":{\n" +
            "            \"iso_language_code\":\"ja\",\n" +
            "            \"result_type\":\"recent\"\n" +
            "         },\n" +
            "         \"source\":\"\\u003ca href=\\\"http:\\/\\/instagram.com\\\" rel=\\\"nofollow\\\"\\u003eInstagram\\u003c\\/a\\u003e\",\n" +
            "         \"in_reply_to_status_id\":null,\n" +
            "         \"in_reply_to_status_id_str\":null,\n" +
            "         \"in_reply_to_user_id\":null,\n" +
            "         \"in_reply_to_user_id_str\":null,\n" +
            "         \"in_reply_to_screen_name\":null,\n" +
            "         \"user\":{\n" +
            "            \"id\":2911880574,\n" +
            "            \"id_str\":\"2911880574\",\n" +
            "            \"name\":\"yuuna\\u263a\\ufe0e\\ufe0e\",\n" +
            "            \"screen_name\":\"princess___214\",\n" +
            "            \"location\":\"\",\n" +
            "            \"description\":\"HS20th\\/\\u767d\\u56e3\\u265b\\ufe0e\\/Dress.M.C\\/\\u526f\\u90e8\\u9577\",\n" +
            "            \"url\":\"https:\\/\\/t.co\\/GsdUikPNcj\",\n" +
            "            \"entities\":{\n" +
            "               \"url\":{\n" +
            "                  \"urls\":[\n" +
            "                     {\n" +
            "                        \"url\":\"https:\\/\\/t.co\\/GsdUikPNcj\",\n" +
            "                        \"expanded_url\":\"http:\\/\\/Instagram.com\\/y14_valentine\",\n" +
            "                        \"display_url\":\"Instagram.com\\/y14_valentine\",\n" +
            "                        \"indices\":[\n" +
            "                           0,\n" +
            "                           23\n" +
            "                        ]\n" +
            "                     }\n" +
            "                  ]\n" +
            "               },\n" +
            "               \"description\":{\n" +
            "                  \"urls\":[\n" +
            "\n" +
            "                  ]\n" +
            "               }\n" +
            "            },\n" +
            "            \"protected\":false,\n" +
            "            \"followers_count\":437,\n" +
            "            \"friends_count\":334,\n" +
            "            \"listed_count\":1,\n" +
            "            \"created_at\":\"Thu Nov 27 13:39:15 +0000 2014\",\n" +
            "            \"favourites_count\":5311,\n" +
            "            \"utc_offset\":null,\n" +
            "            \"time_zone\":null,\n" +
            "            \"geo_enabled\":true,\n" +
            "            \"verified\":false,\n" +
            "            \"statuses_count\":2729,\n" +
            "            \"lang\":\"ja\",\n" +
            "            \"contributors_enabled\":false,\n" +
            "            \"is_translator\":false,\n" +
            "            \"is_translation_enabled\":false,\n" +
            "            \"profile_background_color\":\"C0DEED\",\n" +
            "            \"profile_background_image_url\":\"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\n" +
            "            \"profile_background_image_url_https\":\"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\n" +
            "            \"profile_background_tile\":false,\n" +
            "            \"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/734517819044417537\\/7pc9CYP3_normal.jpg\",\n" +
            "            \"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/734517819044417537\\/7pc9CYP3_normal.jpg\",\n" +
            "            \"profile_banner_url\":\"https:\\/\\/pbs.twimg.com\\/profile_banners\\/2911880574\\/1454847592\",\n" +
            "            \"profile_link_color\":\"0084B4\",\n" +
            "            \"profile_sidebar_border_color\":\"C0DEED\",\n" +
            "            \"profile_sidebar_fill_color\":\"DDEEF6\",\n" +
            "            \"profile_text_color\":\"333333\",\n" +
            "            \"profile_use_background_image\":true,\n" +
            "            \"has_extended_profile\":true,\n" +
            "            \"default_profile\":true,\n" +
            "            \"default_profile_image\":false,\n" +
            "            \"following\":false,\n" +
            "            \"follow_request_sent\":false,\n" +
            "            \"notifications\":false\n" +
            "         },\n" +
            "         \"geo\":null,\n" +
            "         \"coordinates\":null,\n" +
            "         \"place\":null,\n" +
            "         \"contributors\":null,\n" +
            "         \"is_quote_status\":false,\n" +
            "         \"retweet_count\":0,\n" +
            "         \"favorite_count\":0,\n" +
            "         \"favorited\":false,\n" +
            "         \"retweeted\":false,\n" +
            "         \"possibly_sensitive\":false,\n" +
            "         \"lang\":\"ja\"\n" +
            "      },\n" +
            "      {\n" +
            "         \"created_at\":\"Wed May 25 09:07:39 +0000 2016\",\n" +
            "         \"id\":735396902712279040,\n" +
            "         \"id_str\":\"735396902712279040\",\n" +
            "         \"text\":\"20160525 1107 #NowOnm2o: #Verona #EndlessDay #test  Live@ https:\\/\\/t.co\\/r4KLYingPT\",\n" +
            "         \"truncated\":false,\n" +
            "         \"entities\":{\n" +
            "            \"hashtags\":[\n" +
            "               {\n" +
            "                  \"text\":\"NowOnm2o\",\n" +
            "                  \"indices\":[\n" +
            "                     14,\n" +
            "                     23\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"Verona\",\n" +
            "                  \"indices\":[\n" +
            "                     25,\n" +
            "                     32\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"EndlessDay\",\n" +
            "                  \"indices\":[\n" +
            "                     33,\n" +
            "                     44\n" +
            "                  ]\n" +
            "               },\n" +
            "               {\n" +
            "                  \"text\":\"test\",\n" +
            "                  \"indices\":[\n" +
            "                     45,\n" +
            "                     50\n" +
            "                  ]\n" +
            "               }\n" +
            "            ],\n" +
            "            \"symbols\":[\n" +
            "\n" +
            "            ],\n" +
            "            \"user_mentions\":[\n" +
            "\n" +
            "            ],\n" +
            "            \"urls\":[\n" +
            "               {\n" +
            "                  \"url\":\"https:\\/\\/t.co\\/r4KLYingPT\",\n" +
            "                  \"expanded_url\":\"http:\\/\\/www.m2o.it\\/m2o\\/player\",\n" +
            "                  \"display_url\":\"m2o.it\\/m2o\\/player\",\n" +
            "                  \"indices\":[\n" +
            "                     58,\n" +
            "                     81\n" +
            "                  ]\n" +
            "               }\n" +
            "            ]\n" +
            "         },\n" +
            "         \"metadata\":{\n" +
            "            \"iso_language_code\":\"en\",\n" +
            "            \"result_type\":\"recent\"\n" +
            "         },\n" +
            "         \"source\":\"\\u003ca href=\\\"http:\\/\\/www.smarttuner.net\\/preview\\\" rel=\\\"nofollow\\\"\\u003eSTPreview\\u003c\\/a\\u003e\",\n" +
            "         \"in_reply_to_status_id\":null,\n" +
            "         \"in_reply_to_status_id_str\":null,\n" +
            "         \"in_reply_to_user_id\":null,\n" +
            "         \"in_reply_to_user_id_str\":null,\n" +
            "         \"in_reply_to_screen_name\":null,\n" +
            "         \"user\":{\n" +
            "            \"id\":4836300016,\n" +
            "            \"id_str\":\"4836300016\",\n" +
            "            \"name\":\"STPreview\",\n" +
            "            \"screen_name\":\"STPreview\",\n" +
            "            \"location\":\"Milan, Italy\",\n" +
            "            \"description\":\"This is a test account\",\n" +
            "            \"url\":null,\n" +
            "            \"entities\":{\n" +
            "               \"description\":{\n" +
            "                  \"urls\":[\n" +
            "\n" +
            "                  ]\n" +
            "               }\n" +
            "            },\n" +
            "            \"protected\":false,\n" +
            "            \"followers_count\":34,\n" +
            "            \"friends_count\":1,\n" +
            "            \"listed_count\":30,\n" +
            "            \"created_at\":\"Fri Jan 22 20:20:24 +0000 2016\",\n" +
            "            \"favourites_count\":0,\n" +
            "            \"utc_offset\":7200,\n" +
            "            \"time_zone\":\"Rome\",\n" +
            "            \"geo_enabled\":false,\n" +
            "            \"verified\":false,\n" +
            "            \"statuses_count\":31094,\n" +
            "            \"lang\":\"it\",\n" +
            "            \"contributors_enabled\":false,\n" +
            "            \"is_translator\":false,\n" +
            "            \"is_translation_enabled\":false,\n" +
            "            \"profile_background_color\":\"000000\",\n" +
            "            \"profile_background_image_url\":\"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\n" +
            "            \"profile_background_image_url_https\":\"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\n" +
            "            \"profile_background_tile\":false,\n" +
            "            \"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/693936315533004801\\/9uRfAnA1_normal.png\",\n" +
            "            \"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/693936315533004801\\/9uRfAnA1_normal.png\",\n" +
            "            \"profile_banner_url\":\"https:\\/\\/pbs.twimg.com\\/profile_banners\\/4836300016\\/1454970200\",\n" +
            "            \"profile_link_color\":\"4A913C\",\n" +
            "            \"profile_sidebar_border_color\":\"000000\",\n" +
            "            \"profile_sidebar_fill_color\":\"000000\",\n" +
            "            \"profile_text_color\":\"000000\",\n" +
            "            \"profile_use_background_image\":false,\n" +
            "            \"has_extended_profile\":false,\n" +
            "            \"default_profile\":false,\n" +
            "            \"default_profile_image\":false,\n" +
            "            \"following\":false,\n" +
            "            \"follow_request_sent\":false,\n" +
            "            \"notifications\":false\n" +
            "         },\n" +
            "         \"geo\":null,\n" +
            "         \"coordinates\":null,\n" +
            "         \"place\":null,\n" +
            "         \"contributors\":null,\n" +
            "         \"is_quote_status\":false,\n" +
            "         \"retweet_count\":0,\n" +
            "         \"favorite_count\":0,\n" +
            "         \"favorited\":false,\n" +
            "         \"retweeted\":false,\n" +
            "         \"possibly_sensitive\":false,\n" +
            "         \"lang\":\"en\"\n" +
            "      }\n" +
            "   ],\n" +
            "   \"search_metadata\":{\n" +
            "      \"completed_in\":0.051,\n" +
            "      \"max_id\":735396908869537792,\n" +
            "      \"max_id_str\":\"735396908869537792\",\n" +
            "      \"next_results\":\"?max_id=735393252166250495&q=%23test&include_entities=1\",\n" +
            "      \"query\":\"%23test\",\n" +
            "      \"refresh_url\":\"?since_id=735396908869537792&q=%23test&include_entities=1\",\n" +
            "      \"count\":15,\n" +
            "      \"since_id\":0,\n" +
            "      \"since_id_str\":\"0\"\n" +
            "   }\n" +
            "}";
}
